apiVersion: v1
kind: Pod
metadata:
  name: meupod
spec:  
  containers:
    - name: web
      image: fabriocioveronez/web-page:blue
      ports:
        - containerPort: 80

---          
          
apiVersion: v1
kind: Pod
metadata:
  name: meupod-2
  labels:
    app: green  
spec:
  containers:
    - name: web
      image: fabriocioveronez/web-page:green
      ports:
        - containerPort: 80
